Art
andreitr/basedbits pull request #11
Opened 2024-07-24 00:18 UTC by 0xCooki

Still required before deployment:
- Art components
- Art descriptions (both individual components and overall collection description)
- Updated deployment script given additional art components

2024-07-24 22:14 UTC, andreitr requested changes

2024-07-24 22:14 UTC, andreitr commented on src/BBitsEmoji.sol
> +        _mint(msg.sender, currentDay, 1, "");
Or people can simply click the mint button several times?

2024-07-24 22:14 UTC, andreitr commented on src/BBitsEmoji.sol
> +    function userEntry(uint256 _day, uint256 _index) public view returns (Entry memory) {
Can we rename this method to `useEntryByIdex` and add another method to return entry by address `userEntry(uint256 _day, address _user)` ? 

This way I will be able to display user's info in the UI without the need to loop through all the entries.

2024-07-24 22:24 UTC, andreitr requested changes

2024-07-24 22:24 UTC, andreitr commented on src/BBitsEmoji.sol
> +        emit Raffle(currentDay, raffleInfo[currentDay].mints, winner, reward, burned);
rename `Raffle` event to `End`

2024-07-24 22:24 UTC, andreitr commented on src/BBitsEmoji.sol
> +        raffleInfo[currentDay].start = block.timestamp;
Emit `Start(currentDay)` event

2024-07-24 23:11 UTC, 0xCooki commented on src/BBitsEmoji.sol
> +
mint price or duration?

2024-07-24 23:12 UTC, 0xCooki commented on src/BBitsEmoji.sol
> +        if (willMintSettleRaffle()) {
That is how it currently works

2024-07-24 23:13 UTC, 0xCooki commented on src/BBitsEmoji.sol
> +        _mint(msg.sender, currentDay, 1, "");
Yep, you can mint as many times as you want per day

2024-07-25 18:03 UTC, andreitr commented on src/BBitsEmoji.sol
> +        if (willMintSettleRaffle()) {
Oh, I see. So in order to start the new mint a user just need to call the mint function without sending any ETH?

2024-07-25 22:35 UTC, 0xCooki commented on src/BBitsEmoji.sol
> +        if (willMintSettleRaffle()) {
Yep, exactly, and there's a view function `willMintSettleRaffle()` that can tell them ahead of time whether them calling mint will end the raffle and start a new one

2024-08-05 15:35 UTC, merged